# Allowed options are 'instant_scan' and 'daemon_mode'
operation_mode: "instant_scan"

paths:
  scan_target_directory: "/home/lakshy/"
  work_directory: "/tmp/shakti"
  database_directory: "./database"
  rules_file: "../rules.zip" # Allows only zip files. Pack your rules into a zip file.

# Logging configuration
logging:
  enable_console: True
  use_json: True
  enable_file_logging: True
  log_directory: "./logs"
  log_filename: "shakti.log"
  max_size_mb: 50
  max_age_days: 1
  max_backups: 5
  log_level: "info"
  time_format: "UNIXMS" # Zerolog timeformat